# Generated by Django 5.2.14 on 2026-07-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="allergytag",
            name="is_major",
            field=models.BooleanField(default=False),
        ),
    ]
