# Generated by Django 5.2.14 on 2026-07-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_allergytag_is_major"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allergytag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
