# Generated by Django 5.2.14 on 2026-07-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_allergytag_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="allergy",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="core.allergytag"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="end_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
