# Generated by Django 5.2.14 on 2026-07-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_session_allergy_alter_session_end_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="last_edited",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
