# Generated by Django 5.2.14 on 2026-07-30 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_session_created_at_alter_session_end_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
