import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

import apiSidebar from "./docs/myapi/sidebar.js";

// The Introduction is generated as a standard 'doc', while tags are generated as a 'category'.
const apiTagsOnly = apiSidebar.filter((item: any) => item.type === 'category');

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Backend (Django)',
      items: [
        'backend/overview',
        'backend/setup',
        'backend/architecture',
        {
          type: 'category',
          label: 'API',
          items: [
            'backend/api/overview',
            ...apiTagsOnly,
            'backend/api/error-handling',
          ],
        },
        {
          type: 'category',
          label: 'Django Internals',
          items: [
            'backend/django/viewsets',
            'backend/django/serializers',
            'backend/django/permissions',
          ],
        },
      ],
    },
  ],
   
};

export default sidebars;
